#cloud-config

# Dynamic DNS server for instances.
# Makes <instance-id>.instance.encodedcc.org and <name>.instance.encodedcc.org resolve.
# Run on a t2.micro instance with Ubuntu 14.04.
# Security group: ssh-dns.
# IAM role: demo-dns-server.

# $ aws ec2 run-instances --user-data file://instance-dns.yml --security-groups "ssh-dns" --iam-instance-profile Name="demo-dns-server" --image-id ami-5189a661 --instance-type t2.micro --region us-west-2

# Associate elastic-ip address for instance.encodedcc.org NS record.
# $ aws ec2 associate-address --public-ip 52.25.250.155 --region us-west-2 --instance-id i-xxxx

ssh_authorized_keys:
  - %(LOCAL_SSH_KEY)s

runcmd:
- sudo -u ubuntu mv /home/ubuntu/.ssh/authorized_keys /home/ubuntu/.ssh/authorized_keys2
- sudo -u ubuntu aws s3 cp --region=us-west-2 %(S3_AUTH_KEYS)s /home/ubuntu/.ssh/authorized_keys
- set -e
- sudo -u ubuntu GOPATH=/home/ubuntu/gobuild go get github.com/ConradIrwin/aws-name-server
- cp /home/ubuntu/gobuild/bin/aws-name-server /usr/local/bin/
- setcap cap_net_bind_service=+ep /usr/local/bin/aws-name-server
- initctl start aws-name-server

output:
  all: '| tee -a /var/log/cloud-init-output.log'

package_upgrade: true

packages:
- golang
- git
- ntp
- unattended-upgrades
- update-notifier-common

power_state:
  mode: reboot

write_files:
- path: /etc/apt/apt.conf.d/20auto-upgrades
  content: |
    APT::Periodic::Update-Package-Lists "1";
    APT::Periodic::Unattended-Upgrade "1";

- path: /etc/apt/apt.conf.d/50unattended-upgrades
  content: |
    Unattended-Upgrade::Allowed-Origins {
        "${distro_id} ${distro_codename}-security";
    };
    Unattended-Upgrade::Automatic-Reboot "true";

- path: /etc/init/aws-name-server.conf
  content: |
    # upstart script for aws-name-server
    description "AWS Name Server"
    start on filesystem or runlevel [2345]
    stop on runlevel [!2345]
    respawn
    respawn limit 10 5
    setuid nobody
    setgid nogroup
    exec /usr/local/bin/aws-name-server --aws-region us-west-2 --domain instance.encodedcc.org
